#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")/.."

help=$(ghaperf --help)

block='```'

echo "# Usage

<!-- This is generated by scripts/generate-usage.sh. Don't edit this file directly. -->

$block
$help
$block" > USAGE.md
