---
name: autofix.ci
on: pull_request
permissions: {}
jobs:
  autofix:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 15
    steps:
      - uses: suzuki-shunsuke/go-autofix-action@00c2661f4665666ed7c3cb3f8a27725e3e9bf686 # v0.1.10
        with:
          aqua_version: v2.55.1

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod
      - run: |
          go install -ldflags "-X main.version=v0.0.1-0 -X main.commit=$GITHUB_SHA -X main.date=$(date +"%Y-%m-%dT%H:%M:%SZ%:z" | tr -d '+')" ./cmd/ghaperf
      - run: bash scripts/usage.sh
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
